version: "3.8" # версия вашего docker-compose
services: # имеджи, которые запустятся по вашему желанию
  app:
    build: .
    depends_on:
      - db
      - redis
      - minio
    ports:
      - "8079:8080"
    env_file:
      - .env

  db: # название моего имеджа
    image: postgres:12 # скачает image postgres 12 версии
    volumes: # часть настроек для хранения данных, пока для нас это не важно
      - type: volume
        source: postgresdb-data
        target: /var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: RIP_Database
      POSTGRES_PASSWORD: qwerty

  adminer: # adminer db client
    image: adminer
    ports:
      - 8889:8080
    depends_on:
      - db

  minio:
    image: quay.io/minio/minio:RELEASE.2023-12-20T01-00-02Z-cpuv1
    ports:
      - "9901:9001"
      - "9900:9000"
    volumes:
      - minio-data:/data
    environment:
      MINIO_ROOT_USER: Tasks
      MINIO_ROOT_PASSWORD: 123456789
      MINIO_OPTS: --console-address ":9001" --cors-allowed-origins https://dedeimos.github.io
    command: server --console-address ":9001" /data
  
  redis:
    image: redis:6.2-alpine
    restart: always
    command: redis-server --save 20 1 --loglevel warning
    volumes:
      - redis-data:/data

volumes: # часть настроек для хранения данных
  postgresdb-data:
    driver: local
  minio-data:
  redis-data:
    driver: local